name: ESP32 Static Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  static-analysis:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/caiocrux/esp32-tests-ci
    steps:

      - uses: actions/checkout@v4
      - run: ./tools/check-format.sh
      - run: ./tools/check-cppcheck.sh
      - run: ./tools/check-build.sh
